version: '3.9'
services:
    webapi:
      build: .
      restart: always
      ports:
        - "8001:8000"
      volumes:
        - ./app:/app/app
      command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
      depends_on:
        - database
    database:
      image: postgres:14
      restart: on-failure
      healthcheck:
        test: ["CMD", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      volumes:
        - ./database/:/docker-entrypoint-initdb.d/
      env_file:
        - .env
      environment:
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      ports:
        - "5432:5432"
      
    adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
      depends_on:
       - database
